### ISSUE TITLE
Ausreißer

### ISSUE THREAD

**Issue by thomcz** [thomcz/aurora#13]
Entweder Ober und unter Grenze definieren  oder jeden Datensatz individuell betrachten und Ausreißer identifizieren

**Comment by Fenox** [comment]
Überlegen ob die Daten Normalverteilt sind.
Außreißertest aussuchen
z.B. Nalimov-Test, Grub, Dean-Dixon,...
Link: http://www.statistics4u.info/fundstat_germ/cc_outlier_tests.html

**Comment by thomcz** [comment]
Wurde das erledigt? Dann kann mann den Issue schließen :)

**Comment by Fenox** [comment]
Das wurde erledigt
